### PR TITLE
ci: 🎡 update docker manifest images for ownership

### PR DESCRIPTION
**Pull request by 0xc0000007b**

### CODE REVIEW

**Comment by 0xc0000007b** [comment]
Closed to fix in branch under this remote. While working on this Tim helped me discover he was able to issue commits directly to the branch on my repository even when he has no access rights to that repo. The presumption is that GitHub has made that use case possible because I've issued a pull request against the upstream. However, I believe this to be unexpected behavior. Nevertheless, we learned and I've pushed up a different branch on this remote and submitted a new PR for this work.

**Comment by 0xc0000007b** [comment]
Closed to fix in branch under this remote. While working on this Tim helped me discover he was able to issue commits directly to the branch on my repository even when he has no access rights to that repo. The presumption is that GitHub has made that use case possible because I've issued a pull request against the upstream. However, I believe this to be unexpected behavior. Nevertheless, I've pushed up a different branch on this remote and submitted a new PR.

**Comment by rht** [comment]
There is an option "allow edits from maintainers", where if disabled will prevent maintainers to edit the PR and the fork branch if it is not of this repo.

**Comment by 0xc0000007b** [comment]
> There is an option "allow edits from maintainers", where if disabled will prevent maintainers to edit the PR and the fork branch if it is not of this repo.

I thought that meant to the text, not the code! 🤣 So now I know. Thanks @rht.

**Pull request closed without merging**
